---
abstract: 'Access hash entries through methods'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Rick Measham <rickm@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Inflator
provides:
  Hash::Inflator:
    file: lib/Hash/Inflator.pm
    version: 1.100820
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Hash-Inflator
  homepage: http://search.cpan.org/dist/Hash-Inflator/
  repository: http://github.com/hanekomu/Hash-Inflator
version: 1.100820
